# PowerShell script to add all remaining weapons to weapon_config.csv

$weapons = @"
swing_heavy_1,重型挥砍1级,melee,1,1,1,0.8,0.05,1.5,180,1.5,0,15,0.08,0.15,0.1,0,res://scenes/weapons/melee/weapon_melee_sector.tscn,,res://assets/sprites/Weapons/Melee/swing_heavy.png,"swing_heavy1.png,swing_heavy2.png,swing_heavy3.png,swing_heavy4.png",0|0,30|0,1.2|1.0,res://anims/swing_heavy_frames.tres,res://scenes/vfx/swing_heavy_attack.tscn,res://scenes/vfx/swing_heavy_hit.tscn,res://assets/audio/SwingHeavy.wav,sector,,none,60,1,0,0,60,0,0,swing_heavy_2,1,res://assets/sprites/Weapons/Icons/swing_heavy_icon_1.png,""
swing_heavy_2,重型挥砍2级,melee,2,1,1,0.7,0.06,1.5,190,1.6,0,15,0.08,0.15,0.1,0,res://scenes/weapons/melee/weapon_melee_sector.tscn,,res://assets/sprites/Weapons/Melee/swing_heavy.png,"swing_heavy1.png,swing_heavy2.png,swing_heavy3.png,swing_heavy4.png",0|0,30|0,1.3|1.0,res://anims/swing_heavy_frames.tres,res://scenes/vfx/swing_heavy_attack.tscn,res://scenes/vfx/swing_heavy_hit.tscn,res://assets/audio/SwingHeavy.wav,sector,,none,65,1,0,0,65,0,0,swing_heavy_3,2,res://assets/sprites/Weapons/Icons/swing_heavy_icon_2.png,""
swing_heavy_3,重型挥砍3级,melee,3,2,1,0.6,0.07,1.5,200,1.7,0,15,0.08,0.15,0.1,0,res://scenes/weapons/melee/weapon_melee_sector.tscn,,res://assets/sprites/Weapons/Melee/swing_heavy.png,"swing_heavy1.png,swing_heavy2.png,swing_heavy3.png,swing_heavy4.png",0|0,30|0,1.4|1.0,res://anims/swing_heavy_frames.tres,res://scenes/vfx/swing_heavy_attack.tscn,res://scenes/vfx/swing_heavy_hit.tscn,res://assets/audio/SwingHeavy.wav,sector,,none,70,1,0,0,70,0,0,swing_heavy_4,3,res://assets/sprites/Weapons/Icons/swing_heavy_icon_3.png,""
swing_heavy_4,重型挥砍4级,melee,4,2,1,0.5,0.08,1.5,210,1.8,0,15,0.08,0.15,0.1,0,res://scenes/weapons/melee/weapon_melee_sector.tscn,,res://assets/sprites/Weapons/Melee/swing_heavy.png,"swing_heavy1.png,swing_heavy2.png,swing_heavy3.png,swing_heavy4.png",0|0,30|0,1.5|1.0,res://anims/swing_heavy_frames.tres,res://scenes/vfx/swing_heavy_attack.tscn,res://scenes/vfx/swing_heavy_hit.tscn,res://assets/audio/SwingHeavy.wav,sector,,none,75,1,0,0,75,0,0,,4,res://assets/sprites/Weapons/Icons/swing_heavy_icon_4.png,""
circular_vortex_1,旋风斩1级,melee,1,1,1,0.8,0.05,1.5,360,1.5,0,15,0.08,0.15,0.1,0,res://scenes/weapons/melee/weapon_melee_circle.tscn,,res://assets/sprites/Weapons/Melee/circular_vortex.png,"circular_vortex1.png,circular_vortex2.png,circular_vortex3.png,circular_vortex4.png",0|0,0|0,1.2|1.0,res://anims/circular_vortex_frames.tres,res://scenes/vfx/circular_vortex_attack.tscn,res://scenes/vfx/circular_vortex_hit.tscn,res://assets/audio/CircularVortex.wav,circle,,none,0,1,0,0,300,0,0,circular_vortex_2,1,res://assets/sprites/Weapons/Icons/circular_vortex_icon_1.png,""
circular_vortex_2,旋风斩2级,melee,2,1,1,0.7,0.06,1.5,360,1.6,0,15,0.08,0.15,0.1,0,res://scenes/weapons/melee/weapon_melee_circle.tscn,,res://assets/sprites/Weapons/Melee/circular_vortex.png,"circular_vortex1.png,circular_vortex2.png,circular_vortex3.png,circular_vortex4.png",0|0,0|0,1.3|1.0,res://anims/circular_vortex_frames.tres,res://scenes/vfx/circular_vortex_attack.tscn,res://scenes/vfx/circular_vortex_hit.tscn,res://assets/audio/CircularVortex.wav,circle,,none,0,1,0,0,320,0,0,circular_vortex_3,2,res://assets/sprites/Weapons/Icons/circular_vortex_icon_2.png,""
circular_vortex_3,旋风斩3级,melee,3,2,1,0.6,0.07,1.5,360,1.7,0,15,0.08,0.15,0.1,0,res://scenes/weapons/melee/weapon_melee_circle.tscn,,res://assets/sprites/Weapons/Melee/circular_vortex.png,"circular_vortex1.png,circular_vortex2.png,circular_vortex3.png,circular_vortex4.png",0|0,0|0,1.4|1.0,res://anims/circular_vortex_frames.tres,res://scenes/vfx/circular_vortex_attack.tscn,res://scenes/vfx/circular_vortex_hit.tscn,res://assets/audio/CircularVortex.wav,circle,,none,0,1,0,0,340,0,0,circular_vortex_4,3,res://assets/sprites/Weapons/Icons/circular_vortex_icon_3.png,""
circular_vortex_4,旋风斩4级,melee,4,2,1,0.5,0.08,1.5,360,1.8,0,15,0.08,0.15,0.1,0,res://scenes/weapons/melee/weapon_melee_circle.tscn,,res://assets/sprites/Weapons/Melee/circular_vortex.png,"circular_vortex1.png,circular_vortex2.png,circular_vortex3.png,circular_vortex4.png",0|0,0|0,1.5|1.0,res://anims/circular_vortex_frames.tres,res://scenes/vfx/circular_vortex_attack.tscn,res://scenes/vfx/circular_vortex_hit.tscn,res://assets/audio/CircularVortex.wav,circle,,none,0,1,0,0,360,0,0,,4,res://assets/sprites/Weapons/Icons/circular_vortex_icon_4.png,""
"@

Add-Content -Path "config/weapon/weapon_config.csv" -Value $weapons

Write-Host "Added 8 weapon rows successfully"
